/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as FragrancesIndexRouteImport } from './routes/fragrances.index'
import { Route as FragrancesSlugRouteImport } from './routes/fragrances.$slug'
import { Route as HouseIndexRouteImport } from './routes/house.index'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as StockistsIndexRouteImport } from './routes/stockists.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const FragrancesIndexRoute = FragrancesIndexRouteImport.update({
  id: '/fragrances/',
  path: '/fragrances/',
  getParentRoute: () => rootRouteImport,
} as any)
const FragrancesSlugRoute = FragrancesSlugRouteImport.update({
  id: '/fragrances/$slug',
  path: '/fragrances/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseIndexRoute = HouseIndexRouteImport.update({
  id: '/house/',
  path: '/house/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockistsIndexRoute = StockistsIndexRouteImport.update({
  id: '/stockists/',
  path: '/stockists/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fragrances/$slug': typeof FragrancesSlugRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/fragrances/': typeof FragrancesIndexRoute
  '/house/': typeof HouseIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/stockists/': typeof StockistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fragrances/$slug': typeof FragrancesSlugRoute
  '/checkout': typeof CheckoutIndexRoute
  '/fragrances': typeof FragrancesIndexRoute
  '/house': typeof HouseIndexRoute
  '/journal': typeof JournalIndexRoute
  '/stockists': typeof StockistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fragrances/$slug': typeof FragrancesSlugRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/fragrances/': typeof FragrancesIndexRoute
  '/house/': typeof HouseIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/stockists/': typeof StockistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fragrances/$slug'
    | '/checkout/'
    | '/fragrances/'
    | '/house/'
    | '/journal/'
    | '/stockists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fragrances/$slug'
    | '/checkout'
    | '/fragrances'
    | '/house'
    | '/journal'
    | '/stockists'
  id:
    | '__root__'
    | '/'
    | '/fragrances/$slug'
    | '/checkout/'
    | '/fragrances/'
    | '/house/'
    | '/journal/'
    | '/stockists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FragrancesSlugRoute: typeof FragrancesSlugRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  FragrancesIndexRoute: typeof FragrancesIndexRoute
  HouseIndexRoute: typeof HouseIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  StockistsIndexRoute: typeof StockistsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fragrances/': {
      id: '/fragrances/'
      path: '/fragrances'
      fullPath: '/fragrances/'
      preLoaderRoute: typeof FragrancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fragrances/$slug': {
      id: '/fragrances/$slug'
      path: '/fragrances/$slug'
      fullPath: '/fragrances/$slug'
      preLoaderRoute: typeof FragrancesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house/': {
      id: '/house/'
      path: '/house'
      fullPath: '/house/'
      preLoaderRoute: typeof HouseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stockists/': {
      id: '/stockists/'
      path: '/stockists'
      fullPath: '/stockists/'
      preLoaderRoute: typeof StockistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FragrancesSlugRoute: FragrancesSlugRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  FragrancesIndexRoute: FragrancesIndexRoute,
  HouseIndexRoute: HouseIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  StockistsIndexRoute: StockistsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
